AWS_BUCKET: whitehousetechhire2
AWS_ACCESS_KEY_ID: AKIAIAKZWQUWEUU4C42Q
AWS_SECRET_ACCESS_KEY: 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

BING_GEOCODE_ID: AkUo1Fv47ap_DdFq_BQgMYnkDnhgEp-27XAxBU78obRPUUPH5ksbx5yGMvfesIhZ
